package com.example.michael.myapplication;

/**
 *
 * This file contains the output of the 'Caloundra', 'Takeaway' query
 * from the Business Discount Directory data set.
 * This was generated by the prototype Python program 'discounts.py',
 * which is also in our govhack2016b repository.
 *
 * Created by utting on 30/07/2016.
 */
public class DiscountsData {
    public static final String[] HEARING_DISCOUNTS = {
            "Acoustic Hearing Clinics at 39 Minchinton St offers Up to $550 off hearing aids. Free hearing tests.",
            "AudioClinic at 14 Mayes Ave offers $500 disc. on a range of hearing devices. Cond. apply.",
            "Australian Hearing at Shop 3 Ocean View Resort - 115 Bulcock St offers 10% off 'top up' amount for eligible seniors. Cond. apply.",
            "ihear at Shop 2  45 Minchinton St offers 10% off all hearing aid purchases, excluding OHS.",
            "National Hearing Care at Caloundra Village Shopping Centre offers 10% off selected models up to max. $500. No further disc.",
    };

    public static final String[] TAKEAWAY_DISCOUNTS = {
            "Bounce Smoothie & Ice Cream Bar at Grand Pacific Resort - The Esplanade offers 10% discount.",
            "Donut King at Stockland Shp Cnt offers 2 free DK cinnamon donuts when you buy any DK hot drink.",
            "Hungry Jack's Pty Ltd at 53 Caloundra Rd offers Free tea/coffee/sml s'drink with burger or b'fast muffin.",
            "KFC Queensland at 73B Bowman Rd offers Discount not available with promotional or discounted menu items.  See in store for full terms and conditions.",
            "McDonald's Family Restaurants at cnr Fourth Ave/Bowman Rd offers Free small McCafe coffee, small tea or small soft drink with any individual burger or Egg McMuffin purchase. See in store for further details.",
            "Subway Caloundra at 79 Bulcock St offers 10% discount on all subs excluding specials.",
    };
}
